### ISSUE TITLE
OpenApi Validator throws an error for format: phone in the YAML

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/protocol-specifications#371] opened 2023-07-11 09:35 UTC
### Discussed in https://github.com/beckn/protocol-specifications/discussions/368

<div type='discussions-op-text'>

<sup>Originally posted by **shenoyninad** June 27, 2023</sup>
When we put the core specs v1.1.0 through the open API validator, the Support schema throws an error for the properties `callback_phone` and `phone` by specifying that the format of "phone" is unknown. 

<img width="1167" alt="image" src="https://github.com/beckn/protocol-specifications/assets/14144849/be0eb19a-f4f1-414c-a793-c2a2ea1502bf">
</div>

**Comment by emmayank** [comment] 2023-10-30 07:22
unable to replicate the issue. can you please provide more information.

**Comment by emmayank** [comment] 2023-12-07 06:03
Hi @ravi-prakash-v , closing this issue as we are not able to reproduce the same.

**Closed by emmayank** 2023-12-07 06:03 UTC
